name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [ windows-latest ]

    steps:
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Generate projects
      run: |
        cd "${{ github.workspace }}"
        mkdir _build
        cd _build
        cmake .. -G Ninja `
          -DCMAKE_BUILD_TYPE=RelWithDebInfo `
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_DEST_WIN }}\scripts\buildsystems\vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=x64-windows-static `
          -DCMAKE_CXX_COMPILER=cl `
          -DCMAKE_C_COMPILER=cl

    - name: Build
      run: |
        cd "${{ github.workspace }}"
        mkdir _build
        cd _build
        cmake --build