name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [ windows-latest ]

    steps:
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup VS environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Generate projects
      run: |
        mkdir _build
        cd _build
        cmake -G Ninja `
          -DCMAKE_BUILD_TYPE=RelWithDebInfo `
          -DCMAKE_CXX_COMPILER=cl `
          -DCMAKE_C_COMPILER=cl `
          ..

    - name: Build
      run: |
        cmake --build _build

    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: zhm-mod-loader
        path: |
          _build/ZHMModSDK/ZHMModSDK.dll
          _build/ZHMModSDK/ZHMModSDK.pdb
        name: mod-no-pause
        path: |
          _build/Mods/NoPause/NoPause.dll
          _build/Mods/NoPause/NoPause.pdb
        name: mod-skip-intro
        path: |
          _build/Mods/SkipIntro/SkipIntro.dll
          _build/Mods/SkipIntro/SkipIntro.pdb
        name: mod-waking-up-npcs
        path: |
          _build/Mods/WakingUpNpcs/WakingUpNpcs.dll
          _build/Mods/WakingUpNpcs/WakingUpNpcs.pdb