name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [ windows-latest ]

    steps:
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup VS environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Generate projects
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        md _build
        cd _build
        cmake -G Ninja ^
          -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
          -DCMAKE_CXX_COMPILER=cl ^
          -DCMAKE_C_COMPILER=cl ^
          ..

    - name: Build
      run: |
        cd _build
        cmake --build