name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [ windows-latest ]

    steps:
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup VS environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Generate projects
      run: |
        mkdir _build
        cd _build
        cmake -G Ninja `
          -DCMAKE_BUILD_TYPE=RelWithDebInfo `
          -DCMAKE_CXX_COMPILER=cl `
          -DCMAKE_C_COMPILER=cl `
          ..

    - name: Build
      run: |
        cmake --build _build

    - name: Copy SDK and loader artifacts
      run: |
        cd _build
        mkdir _sdk
        Copy-Item ZHMModSDK/ZHMModSDK.dll -Destination _sdk/
        Copy-Item ZHMModSDK/ZHMModSDK.pdb -Destination _sdk/
        Copy-Item DirectInputProxy/dinput8.dll -Destination _sdk/
        Copy-Item DirectInputProxy/dinput8.dll -Destination _sdk/

    - name: Copy mod artifacts
      run: |
        cd _build
        mkdir _mods
        Get-ChildItem -Directory Mods | ForEach-Object { Copy-Item "Mods/$_/$_.dll" -Destination "_mods/$_.dll" }
        Get-ChildItem -Directory Mods | ForEach-Object { Copy-Item "Mods/$_/$_.pdb" -Destination "_mods/$_.pdb" }

    - name: Archive SDK and loader
      uses: actions/upload-artifact@v2
      with:
        name: mod-loader-release
        path: |
          _build/_sdk/*

    - name: Archive mods
      uses: actions/upload-artifact@v2
      with:
        name: mods-release
        path: |
          _build/_mods/*