name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [ windows-latest ]

    steps:
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup VS environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Generate projects
      run: |
        mkdir _build
        cd _build
        cmake -G Ninja `
          -DCMAKE_BUILD_TYPE=RelWithDebInfo `
          -DCMAKE_CXX_COMPILER=cl `
          -DCMAKE_C_COMPILER=cl `
          ..

    - name: Build
      run: |
        cmake --build _build

    - name: Archive SDK
      uses: actions/upload-artifact@v2
      with:
        name: zhm-mod-loader-release
        path: |
          _build/ZHMModSDK/ZHMModSDK.dll
          _build/ZHMModSDK/ZHMModSDK.pdb

    - name: Archive mods
      uses: actions/upload-artifact@v2
      with:
        name: mods-release
        path: |
          _build/Mods/**/*.dll
          _build/Mods/**/*.pdb